spring:
  profiles:
    active: local
  application:
    name: service-api
#    description: "Product Service api"
  jackson:
    time-zone: "Asia/Seoul"

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
      path-mapping:
        health: health

server:
  port: 8080
